# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20180814_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='description', max_length=4000),
        ),
    ]
